name: vaenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.14
  - pip
  - pip:
    - torch==2.9.0
    - torchvision==0.24.0
    - pythae==0.1.2
    - matplotlib==3.10.7
    - scikit-learn==1.7.2
    - numpy==2.3.4

